
---
language: python
python: "2.7"

env:
    - SITE=playbook.yml

install:
    # Install ansible
    - pip install --upgrade pip
    - pip install ansible

before_script:
    # Ensure that Ansible recognizes the short-form role name, rather than the
    # name of the GitHub repo.  For instance, $PWD/../ansible-role-nginx gets
    # symlinked to $PWD/../nginx so the playbook can contain "role: nginx".
    - >
        bash -c 'basename="${PWD##*/}" ; \
            role_name="${basename##*-}" ; \
            ln -sf "$basename" ../"$role_name"'

script:
    # Check syntax
    - "ansible-playbook -l travis test/$SITE --syntax-check"

    # Run the role/playbook with ansible-playbook
    - "ansible-playbook -l travis test/$SITE"

    # Run the role/playbook again, checking for idempotence
    - >
        if ansible-playbook -l travis test/$SITE | grep -q "changed=0.*failed=0"; then
            echo "Idempotence test: pass"
            exit 0
        else
            echo "Idempotence test: fail"
            exit 1
        fi

