---
# Sample playbook for sabnzbd role
- hosts: all
  roles:
    - role: sabnzbd
      sabnzbd_config_settings:
        misc:
          port: 8888
        categories:
          '[*]':
            priority: 0
            pp: 3
            name: '*'
            script: None
            newzbin: ''
            dir: ''
