---
- name: install python-apt
  apt:
    name: python-apt
    state: present
    update_cache: yes

- name: install sabnzbd repository
  apt_repository:
    repo: 'ppa:jcfp/ppa'
    state: present

- name: install sabnzbd
  apt:
    name: "{{ sabnzbd_pkg }}"
    state: present
    update_cache: yes
