---
- name: build list of items in sabnzbd config
  set_fact:
    sabnzbd_config_items: >
      {%- set _sabnzbd_config_items = [] -%}
      {%- for section, options in sabnzbd_config_settings.iteritems() -%}
        {%- if options -%}
          {%- for option, value in options.iteritems() -%}
            {%- set _null = _sabnzbd_config_items.append({
              'section': section,
              'option': option,
              'value': value
            }) -%}
          {%- endfor -%}
        {%- else -%}
          {%- set _null = _sabnzbd_config_items.append({
            'section': section,
          }) -%}
        {%- endif -%}
      {%- endfor -%}
      {{ _sabnzbd_config_items }}
  tags:
    - sabnzbd
  tags:
    - sabnzbd
    - config

- name: insert dummy section to prevent parser error on top-level key(s)
  become: yes
  lineinfile:
    dest: "{{ sabnzbd_config_src }}"
    line: '[ ]'
    insertbefore: BOF
    state: present
  tags:
    - sabnzbd
    - config

- name: alter sabnzbd config file
  become: yes
  ini_file:
    backup: "{{ sabnzbd_config_backup | default(omit) }}"
    dest: "{{ sabnzbd_config_src }}"
    follow: "{{ sabnzbd_config_follow | default(omit) }}"
    group: "{{ sabnzbd_config_group | default(omit) }}"
    mode: "{{ sabnzbd_config_mode | default(omit) }}"
    owner: "{{ sabnzbd_config_owner | default(omit) }}"
    selevel: "{{ sabnzbd_config_selevel | default(omit) }}"
    serole: "{{ sabnzbd_config_serole | default(omit) }}"
    setype: "{{ sabnzbd_config_setype | default(omit) }}"
    option: "{{ item.option | default(omit) }}"
    value: "{{ item.value | default(omit) }}"
    section: "{{ item.section | default(omit) }}"
  with_items: "{{ sabnzbd_config_items }}"
  when: sabnzbd_config_items is defined
  tags:
    - sabnzbd
    - config

- name: remove dummy section
  become: yes
  lineinfile:
    dest: "{{ sabnzbd_config_src }}"
    regexp: '^\s*\[ \]\s*$'
    state: absent
  tags:
    - sabnzbd
    - config

- name: move existing sabnzbd.ini to fragments dir
  fetch:
    dest: "{{ sabnzbd_config_fragments_dir }}/000-{{ sabnzbd_config_src | basename}}"
    src: "{{ sabnzbd_config_src }}"
    flat: yes
  when: >
    sabnzbd_config_fragments_dir is defined
  tags:
    - sabnzbd
    - config

- name: assemble sabnzbd config file
  become: yes
  assemble:
    backup: "{{ sabnzbd_config_backup | default(omit) }}"
    dest: "{{ sabnzbd_config_src }}"
    follow: "{{ sabnzbd_config_follow | default(omit) }}"
    group: "{{ sabnzbd_config_group | default(omit) }}"
    mode: "{{ sabnzbd_config_mode | default(omit) }}"
    owner: "{{ sabnzbd_config_owner | default(omit) }}"
    selevel: "{{ sabnzbd_config_selevel | default(omit) }}"
    serole: "{{ sabnzbd_config_serole | default(omit) }}"
    setype: "{{ sabnzbd_config_setype | default(omit) }}"

    remote_src: "{{ sabnzbd_config_remote_src | default(omit) }}"
    src: "{{ sabnzbd_config_fragments_dir }}"
  when: sabnzbd_config_fragments_dir is defined
  tags:
    - sabnzbd
    - config

