---
# tasks file for sabnzbd
- include: packer.yml
  when: ansible_pkg_mgr == 'pacman'
  tags:
    - sabznbd
    - pacman
    - packer

- include: sabnzbd_config.yml
  tags:
    - sabnzbd
    - config

- include: service.yml
  tags:
    - sabnzbd
    - service
