---
# tasks file for sabnzbd
- include: packer.yml
  when: ansible_pkg_mgr == 'pacman'
  tags:
    - sabznbd
    - pacman
    - packer

- name: check whether sabnzbd.ini exists
  stat:
    path: "{{ sabnzbd_config_src }}"
    follow: yes
  register: sabnzbd_config_stat
  tags:
    - sabnzbd
    - config
    - generate

- include: generate.yml
  when: not sabnzbd_config_stat.stat.exists
  tags:
    - sabnzbd
    - config
    - generate

- include: assemble.yml
  when: sabnzbd_config_assemble is defined and sabnzbd_config_assemble | bool
  tags:
    - sabnzbd
    - config
    - assemble

    #- include: sabnzbd_config.yml
    #  tags:
    #    - sabnzbd
    #    - config
    #    - ini_file
