---
# tasks file for sabnzbd

# TODO use loop_control/loop_var here.  Can't do this ATM because of
# https://github.com/ansible/ansible/issues/17101
- name: include relevant vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_pkg_mgr | default("dummy") | replace("pacman", "packer") }}.yml'
        - dummy.yml
      paths:
        - '{{ role_path}}/vars'
    - files:
        - '{{ ansible_os_family | default("dummy") }}.yml'
        - dummy.yml
      paths:
        - '{{ role_path}}/vars'
    - files:
        - '{{ ansible_distribution | default("dummy") }}.yml'
        - dummy.yml
      paths:
        - '{{ role_path}}/vars'
  tags:
    - always

- name: include Packer tasks
  include: packer.yml
  when: ansible_pkg_mgr == 'pacman'
  tags:
    - pacman
    - package
    - packer
    - sabnzbd.pacman
    - sabnzbd.package
    - sabnzbd.packer

- name: include Apt tasks
  include: apt.yml
  when: ansible_pkg_mgr == 'apt'
  tags:
    - apt
    - package
    - sabnzbd.apt
    - sabnzbd.package

- name: include YUM tasks
  include: yum.yml
  when: ansible_pkg_mgr == 'yum'
  tags:
    - package
    - yum
    - sabnzbd.package
    - sabnzbd.yum
