---
- name: add options to sabnzbd.ini
  sabnzbd_config:
    dest: "{{ sabnzbd_config_dest }}"
    settings: "{{ sabnzbd_config_settings | default(omit) }}"
    follow: "{{ sabnzbd_follow | default(omit) }}"
    group: "{{ sabnzbd_group }}"
    mode: "{{ sabnzbd_file_mode }}"
    owner: "{{ sabnzbd_owner }}"
    selevel: "{{ sabnzbd_selevel | default(omit) }}"
    serole: "{{ sabnzbd_serole | default(omit) }}"
    setype: "{{ sabnzbd_setype | default(omit) }}"
    seuser: "{{ sabnzbd_seuser | default(omit) }}"
  tags:
    - sabnzbd
    - config
