---
- include: yum_RedHat.yml
  when: ansible_distribution != 'Fedora'

- include: yum_Fedora.yml
  when: ansible_distribution == 'Fedora'

- name: install sabnzbd
  yum:
    name: "{{ sabnzbd_pkg }}"
    state: present
  tags:
    - sabnzbd
    - apt
