---
# handlers file for sabnzbd

- name: get post-run stat of sabnzbd config
  stat:
    follow: "{{ sabnzbd_config_follow | default(omit) }}"
    get_checksum: yes
    path: "{{ sabnzbd_config_dest }}"
  register: sabnzbd_config_st_post
  changed_when: sabnzbd_service_restarted_on_change | bool
  notify:
    - compare sabnzbd config checksums
  tags:
    - sabnzbd
    - config
    - service

- name: compare sabnzbd config checksums
  debug: trigger sabnzbd restart
  changed_when: >
    ((not sabnzbd_config_st_pre.exists) and sabnzbd_config_st_post.exists) or
    (sabnzbd_config_st_pre.stat.checksum != sabnzbd_config_st_post.stat.checksum)
  notify: restart sabnzbd service
  tags:
    - sabnzbd
    - config
    - service

- name: restart sabnzbd service
  service:
    arguments: "{{ sabnzbd_service_arguments | default(omit) }}"
    name: "{{ sabnzbd_service_name }}"
    pattern: "{{ sabnzbd_service_pattern | default(omit) }}"
    runlevel: "{{ sabnzbd_service_runlevel | default(omit) }}"
    sleep: "{{ sabnzbd_service_sleep | default(omit) }}"
    state: restarted
  tags:
    - sabnzbd
    - service
